### ISSUE TITLE
Please add support to change color

### ISSUE THREAD

**Issue by hronek** [Fraasi/Saeae#2]
I see wrong the blue color on my black backgroudn. Can you add support to change color?

**Comment by Fraasi** [comment]
Can you please be more specific. I know the  tray temperature is a little hard to see on some machines/backgrounds. I originally made this for a friend in one afternoon, and updated it a little bit. But i'm thinking of doing a major update when i get to it.
What version are you using?

**Comment by Fraasi** [comment]
Closing this as latest release has totally rewritten tray icon temperature which is much clearer than the old one. See readme for pictures.
